### ISSUE TITLE
remove backend folder

### ISSUE THREAD

**Issue by PaulBredl** [PaulBredl/meta-configurator#362]
We don't need the backend folder anymore.
Also move the frontend folder to top level

**Comment by Keyshal-211** [comment]
@PaulBredl  I removed backend folder but second point you mean, we don't need config assistant folder under frontend.

**Comment by PaulBredl** [comment]
yes we dont need a frontend folder, can be just config-assistant

**Comment by PaulBredl** [comment]
We do not want to merge now because of many merge conflicts this will create (see pull request)
